# Generated by Django 4.2.17 on 2025-01-09 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProdductImageModel',
            new_name='ProductImageModel',
        ),
    ]
