# Generated by Django 4.2.17 on 2025-01-09 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_rename_prodductimagemodel_productimagemodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productmodel',
            old_name='descrption',
            new_name='description',
        ),
    ]
